language: ruby
cache: bundler
rvm:
- 2.4.1
install: gem install jekyll html-proofer
before_script:
- chmod +x ./scripts/travis-build
script: "./scripts/travis-build"
branches:
  only:
  - www
  - beta
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
- provider: firebase
  token:
    secure: NA+TODC4bPWzkzB8SjdNShxqhACejgQpw1jbmMOQJBIV3cTLekAjHDmKnuwUlNOERtYcTZequuCw+/EjBN5lxSbXVITSf7VwniFnsGA2BIDNyShEhXvp1d9BG+UXvsVBissDlY2UqG+Twl/fE6VALnzd+NAYZCHZubYpYVPcJvLCLZ4d/zjIFW/rQDXxfAjzchLwJhDvUZroHY8BJWSjayErIpTP/1PFmK0YNUhDwp7vj650SJ+IcKZGBQuIogiGjxvcw2Myvr1a15RTKGRJ2DB43XHTlw+bruDQGlgbW/wymmmOHwUd/xgks8Mk4743C88Mt/J1+Sb8ntK/k9Fm9BwX5qo2qu/vtu5pHVbwjhIDCyIK96h1Op6e/AWOVTkkKPxdB1lSOz7IfdRpkgO9m+3BUBmqL3ZFXov9UtHEJ1EaP6cwOyxBTS4AewjDdqvr7u9QdYot8YSsncp8x5deb+dqe8x5kisSQCReX7mFqOQuwljkLByDs7J7RusL5TVZtVExjQxdcACDPtjOb7LU6kPBeNJZusoiz90/U7mKCI9iWCN6GpMB/xzqgS1opNVuMNSgpSXurVoAEJ+KLNEEjNPVd9BvWttlvli2hGaqwly60WHh8yYUs6W56xfOyMYsyxR7U1y448S2FqFrFe2DjVrEACP0xDlRavnWRnL1qnY=
  skip_cleanup: true
  project: rutherford-nj
  local-dir: _site
  on:
    repo: rutherford-nj/www.rutherford-nj.com
    branch: www
- provider: firebase
  token:
    secure: NA+TODC4bPWzkzB8SjdNShxqhACejgQpw1jbmMOQJBIV3cTLekAjHDmKnuwUlNOERtYcTZequuCw+/EjBN5lxSbXVITSf7VwniFnsGA2BIDNyShEhXvp1d9BG+UXvsVBissDlY2UqG+Twl/fE6VALnzd+NAYZCHZubYpYVPcJvLCLZ4d/zjIFW/rQDXxfAjzchLwJhDvUZroHY8BJWSjayErIpTP/1PFmK0YNUhDwp7vj650SJ+IcKZGBQuIogiGjxvcw2Myvr1a15RTKGRJ2DB43XHTlw+bruDQGlgbW/wymmmOHwUd/xgks8Mk4743C88Mt/J1+Sb8ntK/k9Fm9BwX5qo2qu/vtu5pHVbwjhIDCyIK96h1Op6e/AWOVTkkKPxdB1lSOz7IfdRpkgO9m+3BUBmqL3ZFXov9UtHEJ1EaP6cwOyxBTS4AewjDdqvr7u9QdYot8YSsncp8x5deb+dqe8x5kisSQCReX7mFqOQuwljkLByDs7J7RusL5TVZtVExjQxdcACDPtjOb7LU6kPBeNJZusoiz90/U7mKCI9iWCN6GpMB/xzqgS1opNVuMNSgpSXurVoAEJ+KLNEEjNPVd9BvWttlvli2hGaqwly60WHh8yYUs6W56xfOyMYsyxR7U1y448S2FqFrFe2DjVrEACP0xDlRavnWRnL1qnY=
  skip_cleanup: true
  project: rutherford-nj-beta-site
  local-dir: _site
  on:
    repo: rutherford-nj/www.rutherford-nj.com
    branch: beta
