sudo: required

language: ruby

cache:
  bundler: true
  directories:
    - node_modules

rvm:
- 2.4.1


script: make deploy


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: LRN6B8uQUcWiR74XJuJPoaUnfeekNm/InWyVxbW10hNktHCW8xazpygg85wnGP2Z4rDeWg4dn+zUHzr8VG5GXs4Liu4Sl0AGdOMIt5F1TOB/qrEVR2NFX8qc7D/D7FMCy9+0AwQW2x/vMHEokwa7u9+0vJH8J7W2b6uYr8lfPy9+uiXALWjA27oOq3iQvJ9y5YpyJNiQ3qV0D+dft1qKGR05LZmEE/DCV4xFhFG5L8WYs1sWeoZjc/tySClXfhKrdkn2KeYwDepkowaAzcPsHz+87MpOTXofavd0L4ZSZJihMSlPPYXGBEmejN3YMAIZwp8efIRab+YeAQv49kKMOo7X2VgidUab7deYuZvQnRtqB3iDIb6bDkWi2PoKs3rh38I0sQmG98MNvPJsQ9YAqZ7kUTD82kB+MCQb13QjJ0R1j1TZ6ip1GcORMVNz5UjMr90CGxds+A9m/M5hOzLq9v8t8T5T7PrpHwwmDEA5oA2Xmo3KD2TVMYQQPL9IygqBO0CIvbFcd67Q3IB5wJ/KF2r1M40q6jXrDFArUq3zsF+JAC6ijkgs/oSRr6X2CVSsUxO9motNKbc6JqaqAPnJ03eSfJb/sPO1v3xWoQa7BZdO8H22qK5pA3rmcjQwe4ChWhQiMMpo8DeNGbrvngLPTPC9X+rFX02DPDXG+w1TlP0=

deploy:
  skip_cleanup: true

notifications:
  slack:
    secure: t/VwCHLxef6I1ugtyvXKX7pW0OKM+0mjG0waHwht37hY6KGzLaI+xztffTFbLJ9T2AHMIdI65HZkAxaH8V85GnCVIHWjSd1J21mOIfU0NN76W4l/VRdTw0O1P1pttLh3Xadshap7tJbAaIuf/vdyt0W7un7YBONd/pTALy/XpSGO0UVbGnY/KufnegJzGWO6cdOuxlxb5Mesw2+4nfEtz1Tu+Ag6OrqucZVGQ5fcsrlbGeG6+lrcO9stDfKq16WdiytEDUl7+Z0IbYExaNOPGK4aK312KJ0ayrHp/Y2H1dVCEGSSsmEYtZIa1u+DY8a0VIMzrVvdgmNPQwaLrXETrJ11VBhqmmyJNq/5MG8d6wbXnC0qZ2SwOaPiSKYcGGzOj9yonRi1BXT9jaRb72ow8Wv/qD6WvgMafVcbMqZNZu5f/kVQCknzLcErsEDs/v8VPKiGZvGu0l9M+hHrwzowa7kF78bwHLxX3davsCeJP2KIhpk4Z7+PpdsaZSGhmndiqdT0SJFYwgxRGf6qDsWSYnUm+jdGcFqhmcDyVgqxQ48h1tlAZc4wMh3X2VRDdeTQ/poArKDZfzTrdrSSg2Dug+m7OoaIomLD/2WpToK7D4YYD83RcuMF1kmPdCHyEUnBItNtluD2FZOMS58GKBxoo1JtfLIr2BRhTPuZnV13xpE=
